[package]
name = "macmon"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
crossterm = "0.29.0"
humantime = "2.3.0"
ratatui = "0.29.0"
sysinfo = "0.37.2"
tokio = { version = "1.48.0", features = ["full"] }
walkdir = "2.5.0"
